vapor/postgres-kit

Sources/PostgreSQL/Data/PostgreSQLArrayCustomConvertible.swift, Sources/PostgreSQL/Data/PostgreSQLData+BinaryFloatingPoint.swift, Sources/PostgreSQL/Data/PostgreSQLData+Bool.swift, Sources/PostgreSQL/Data/PostgreSQLData+Data.swift, Sources/PostgreSQL/Data/PostgreSQLData+Date.swift, Sources/PostgreSQL/Data/PostgreSQLData+FixedWidthInteger.swift, Sources/PostgreSQL/Data/PostgreSQLData+Optional.swift, Sources/PostgreSQL/Data/PostgreSQLData+Point.swift, Sources/PostgreSQL/Data/PostgreSQLData+String.swift, Sources/PostgreSQL/Data/PostgreSQLData+UUID.swift, Sources/PostgreSQL/Data/PostgreSQLDataCustomConvertible.swift, Sources/PostgreSQL/Data/PostgreSQLJSONCustomConvertible.swift, Sources/PostgreSQL/DataType/PostgreSQLDataType.swift, Sources/PostgreSQL/Utilities.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
Adds support for `T[]` columns, and a protocol for extending this support beyond Swift arrays.
=> array support

Package.swift, Sources/PostgreSQL/Connection/PostgreSQLConnection+Authenticate.swift, Sources/PostgreSQL/Connection/PostgreSQLConnection.swift, Sources/PostgreSQL/Message+Serialize/PostgreSQLMessageEncoder.swift, Sources/PostgreSQL/Message/PostgreSQLAuthenticationRequest.swift, Sources/PostgreSQL/Message/PostgreSQLMessage.swift, Sources/PostgreSQL/Message/PostgreSQLPasswordMessage.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
=> password support

Sources/PostgreSQL/Connection/PostgreSQLConnection+Query.swift, Sources/PostgreSQL/Connection/PostgreSQLConnection+SimpleQuery.swift, Sources/PostgreSQL/Connection/PostgreSQLConnection.swift, Sources/PostgreSQL/Data/PostgreSQLJSONCustomConvertible.swift, Sources/PostgreSQL/Message+Parse/PostgreSQLMessageDecoder.swift, Sources/PostgreSQL/Message+Serialize/PostgreSQLMessageEncoder.swift
Replaced a lot of fatalErrors by throwing `PostgreSQLError`s when possible. 
Also removed the `infix operator !!` by throwing the corresponding error if a guard statement fails.
This closes #14.
=> Replace fatalErrors() by throwing errors

Sources/PostgreSQL/Message+Serialize/PostgreSQLMessageEncoder.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
Fixes a bug that improperly encoded `null` binary binds.
=> null data encode

Sources/PostgreSQL/Data/PostgreSQLDataCustomConvertible.swift
Helper extension to enable simple enums to be created from their base types stored in SQL 🎷
=> Adds conformance to RawRepresentable to ease enum encoding

Sources/PostgreSQL/Data/PostgreSQLData+Date.swift
Note that I have not made parsing the textual format of the timestamp type more accurate - do we need that? If so, where is that format documented?
=> Add support for persisting dates with microsecond precision

Sources/PostgreSQL/Connection/PostgreSQLConnection.swift
`PostgreSQLTableNameCache` holds a `PostgreSQLConnection` future. Once that future is fulfilled, it strongly holds a reference to `PostgreSQLConnection`. That connection in turn holds the table name cache, so we have a reference cycle. This causes the table name cache and its connection to never get released. This is relevant when testing, if the tests are set up such that each test creates a new `Database`.
=> Fix a memory leak in `PostgreSQLConnection`

Sources/PostgreSQL/Connection/PostgreSQLConnection.swift
Otherwise, the connection is never claused, and PostgreSQL might complain about too many open connections.
=> Close a `PostgreSQLConnection`'s channel on deinit.

Sources/PostgreSQL/Database/PostgreSQLDatabaseConfig.swift
Saves a config option, especially helpful for things like Vapor Cloud
=> Default Postgres port to 5432 when not supplied

Sources/PostgreSQL/Connection/PostgreSQLConnection+NotifyAndListen.swift, Sources/PostgreSQL/Connection/PostgreSQLConnection.swift, Sources/PostgreSQL/Message/PostgreSQLNotificationResponse.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
@tanner0101  sorry about the terrible confusion
=> Notify listen

Sources/PostgreSQL/Data/PostgreSQLColumn.swift, Sources/PostgreSQL/Message+Parse/PostgreSQLMessageDecoders.swift, Sources/PostgreSQL/Message/PostgreSQLRowDescription.swift
"The oid type is currently implemented as an unsigned four-byte integer" as per https://www.postgresql.org/docs/current/static/datatype-oid.html
=> Fix Int32 -> UInt32 OIDs

.gitignore, Sources/PostgreSQL/Data/PostgreSQLData+Point.swift, Sources/PostgreSQL/Database/PostgreSQLTransportConfig.swift, Sources/PostgreSQL/Utilities.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift, circle.yml, docker-compose.yml
Fixes https://github.com/vapor/postgresql/issues/55
=> remove executing code from asserts

Sources/PostgreSQL/Data/PostgreSQLData+String.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
Numeric numbers with a fractional part with a leading zero (eg: 10.08) will be decoded from the database without the leading zero (ie: 10.80).
This is a serious issue which results in corrupted numeric values.
=> Fix numeric with leading zero fractional

Sources/PostgreSQL/Data/PostgreSQLJSONCustomConvertible.swift
Fix bug when user tries to save JSONB (most time it shows when trying to save an array) and receive an error: `unsupported jsonb version number 123`. PostgreSQL requires JSONB version number in a first byte.
https://doxygen.postgresql.org/jsonb_8c_source.html#l00104:
>  **jsonb type recv function**
> The type is sent as text in binary mode, so this is almost the same as the input function, but it's prefixed with a version number so we can change the binary format sent in future if necessary. For now, only version 1 is supported.
Current code (before PR) is not working, you can see the error in updated test [at CircleCI](https://circleci.com/gh/vapor/fluent-postgresql/191?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
Updated test is located in PR …
=> Add JSONB version to PostgreSQLJSONCustomConvertible

Sources/PostgreSQL/Codable/PostgreSQLValueEncoder.swift, Sources/PostgreSQL/SQL/PostgreSQLUpsert.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
The current algorithm has a logical error that causes unkeyed data to be encoded as single values. This caused issues serializing arrays of enums in FluentPostgreSQL.
=> fix nested unkeyed encoding data

Sources/PostgreSQL/SQL/PostgreSQLBinaryOperator.swift
This fixes the RegExp operator. PostgreSQL uses `~` and not `REGEXP`.
=> Fix regexp operator

Sources/PostgreSQL/Data/PostgreSQLData+FixedWidthInteger.swift
OID doesn’t fit in so we had to bump it up to UInt32
=> Fix OID decoding as UInt32

Sources/PostgreSQL/SQL/PostgreSQLBinaryOperator.swift
Fixes https://github.com/vapor/postgresql/issues/98
There are a lot of binary operators in Postgres. Trying to catch them all in an enum seems very optimistic. Especially given that enums can't be extended with extra cases by the user.
Adding a `custom` case will allow the user to provide the operator in case the operator is not included in the enum already.
=> Allow custom binary operators

Sources/PostgreSQL/Connection/PostgreSQLConnection+TableNameCache.swift
Adds an option for refreshing the table name cache.
=> allow table name refresh

Sources/PostgreSQL/Data/PostgreSQLData+String.swift
**TL;DR**
In cases we have table's fields a `numeric` type and value have zero, we get error 
```console
<unknown>:0: error: -[AppTests.TestTest testSum] : failed: caught error: ⚠️ [PostgreSQLError.decode: Could not decode Int: 0x0000000000000000 (NUMERIC).]
``` 
linked issue https://github.com/vapor/fluent/issues/570
**Explain**  
1. Model
```swift
final class TestTable: PostgreSQLModel {
var id: Int?
var name: String
var score: Int
init(
id: Int? = nil,
name: String,
score: Int = 0
) throws {
self.id = id
self.name = name
self.score = score
}
}
extension TestTable: Migration {
public static func prepare(on connection: PostgreSQLConnection) -> Future<Void> {
return PostgreSQLDatabase.create(self, on: connection) { builder in
builder.field(for: \.id, isIdentifier: true)
builder.field(for: …
```
=> Fix work convertFromPostgreSQLData for Numeric type with zero value

Sources/PostgreSQL/Data/PostgreSQLData+String.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
Adds a failing test case for the issue fixed in https://github.com/vapor/postgresql/pull/109.
=> add failing test case for 0 numeric value

Package.swift
SQLConnectable protocol is undeclared in SQL 2.0.2.
=> Update SQL dependency to 2.1.0

Sources/PostgreSQL/Data/PostgreSQLData+String.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
Fixes a bug causing zeros to be stripped from numeric values such as 10234.543201, producing 1234.54321.
=> Fix zeros stripped in conversion from numeric

Sources/PostgreSQL/SQL/PostgreSQLBinaryOperator.swift
Some operators to especially compare arrays are missing in the current PostgreSQLBinaryOperator struct.
https://www.postgresql.org/docs/current/functions-array.html
=> Add missing array operators

Sources/PostgreSQL/Connection/PostgreSQLConnection.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
By adding a handler that retains self on the channel's close future, the connection gets retained until the channel is closed. We break the retain cycle by using a weak reference to self. The completion handler in `send(:onResponse:)` is enough to ensure that the connection stays alive while a message is sent to the server.
=> Fix a retain cycle in PostgreSQLConnection

Sources/PostgreSQL/Codable/PostgreSQLValueEncoder.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
=> Fix empty keyed encoding

Sources/PostgreSQL/Data/PostgreSQLData+Point.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
Fixes `PostgreSQLPoint` endianness when using binary encoding. Fixes #125.
=> point endianness fix

Sources/PostgreSQL/Column/PostgreSQLDataTypeCode.swift, Sources/PostgreSQL/Data/PostgreSQLData+Polygon.swift, Sources/PostgreSQL/SQL/PostgreSQLDataTypeStaticRepresentable.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
I didn't write any tests yet and I think the "reverse" code can be slightly simplified from your Point fix.  I'll let you handle that when you add tests.
I did test it by using it.
=> added polygon data-type

Sources/PostgreSQL/Data/PostgreSQLData+Date.swift, Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift
It seems `timestamp` values are adjusted for the local time zone.
When converting to a `Date`, we need to subtract the local offset to get the correct value.
When converting from a `Date`, it is better to use the `timestamptz` type, which works with both kinds of fields and does not have this problem.
=> Fix conversion between Date and timestamp/timestamptz types

Sources/PostgreSQL/Codable/PostgreSQLRowDecoder.swift, Sources/PostgreSQL/Column/PostgreSQLColumn.swift, Sources/PostgreSQL/Connection/PostgreSQLConnection+TableNameCache.swift
Motivation:
1. `PostgreSQLRowDecoder`: `_KeyedDecodingContainer.decode` is called once for each key on the decoded object. With the current implementation, this performs a linear search on the `row` dictionary, which results in a total runtime (per object) of O(keys * columns), i.e. quadratic runtime ~O(keys^2). We replace the current linear search with one or two dictionary lookups if `tableOID != 0`, resulting in linear runtime (per object) in the number of keys (provided dictionary lookups can be assumed to take roughly constant time).
2. `PostgreSQLConnection.TableNameCache`: Most lookups are `tableName -> OID`. We accelerate that lookup by preparing a dictionary for that kind of lookup ahead of time, again replacing linear search.
Effect:
The time required for decoding ~5k objects …
=> Significantly improve performance of row decoding.

Sources/PostgresKit/PostgresConnectionSource.swift
Fixes an issue in `PostgresConnectionSource` where the connection would not be closed (resulting in an assertion) if an error happened during authentication.
=> close conn if auth fails

.gitignore, Sources/PostgreSQL/Utilities/PostgreSQLError.swift
Fixes https://github.com/vapor/postgres-kit/issues/146
=> make stacktrace optional

.github/workflows/test.yml, Sources/PostgresKit/PostgresDataDecoder.swift, Sources/PostgresKit/PostgresDataEncoder.swift, Sources/PostgresKit/PostgresRow+SQL.swift, Tests/PostgresKitTests/PostgresKitTests.swift
Refactors `PostgresDataEncoder` to be more flexible. There are now three distinct paths for encoding:
- Single value: Cast to `PostgresDataConvertible`, if fail, unwrap and try again
- Unkeyed value: Convert to `JSONB[]`
- Keyed value: Convert to `JSONB`
This is achieved by encoding to a temporary structure. This structure can be analyzed when deciding how to proceed with encoding.
=> postgres data encoder refactor

Sources/PostgresKit/PostgresConfiguration.swift
- Adds support for URLs with scheme `postgres://` _and_ `postgresql://`
- Adds support for `sslmode=require` query string
- TLS certificate verification is now enabled by default
=> Improved PostgresConfiguration(url:) support

Sources/PostgresKit/PostgresConfiguration.swift
Add support for configuring connections via UNIX domain socket (#170).
```swift
PostgresConfiguration(
unixDomainSocketPath: "/tmp/.s.PGSQL.5432",
username: "postgres",
password: "postgres",
database: "postgres"
)
```
=> Add support for configuring connections via UNIX domain socket

.github/workflows/test.yml, Sources/PostgresKit/PostgresDataDecoder.swift, Sources/PostgresKit/PostgresDataEncoder.swift
Adds support for encoding arrays that contain values besides nested structs (JSON and JSONB).
=> support encoding arrays other than json

Sources/PostgresKit/ConnectionPool+Postgres.swift, Tests/PostgresKitTests/PostgresKitTests.swift
Adds a method for creating a `PostgresDatabase` from an `EventLoopGroupConnectionPool`.
```swift
let db = pool.database(logger: .init(label: "test"))
```
=> Add EventLoopGroupConnectionPool database convenience

Sources/PostgreSQL/Codable/PostgreSQLDataDecoder.swift
Fixes `JSON` / `JSONB` decoding for text and binary serializations (#177).
=> Fix assertion while decoding JSON (non-JSONB)

Sources/PostgreSQL/SQL/PostgreSQLBinaryOperator.swift
Fixes the `notRegexp` operator and adds the two case-insensitive variants (#139, #90).
See [the pgsql docs](https://www.postgresql.org/docs/10/functions-matching.html#FUNCTIONS-POSIX-REGEXP) for reference.
=> Fix not-regexp operator, add case insensitive regexp operators

Sources/PostgresKit/PostgresConfiguration.swift
Adds support for database urls not containing an explicit port: `postgres://user:password@localhost/database` (#183).
=> Use default port for URLs

Sources/PostgresKit/PostgresDataDecoder.swift
Replaces a force unwrap with a `DecodingError` in `PostgresDataDecoder` (#184).
=> Fix force unwrap in PostgresDataDecoder

Tests/PostgresKitTests/PostgresKitTests.swift
No semver label needed, doesn't need a release
=> Make tests respect the LOG_LEVEL env var

Package.swift, Sources/PostgresKit/PostgresDialect.swift
Support for the RETURNING clause was added in SQLKit 3.5.0 (#189). 
This enables that functionality for Postgres by setting the `SQLDialect` feature flag.
=> Enable RETURNING use in SQLKit

Sources/PostgresKit/PostgresColumnType.swift
Fixes typo in `PostgresColumnType.interval`'s string serialization (#194, fixes #193).
=> Fix PostgresColumnType.interval typo

Sources/PostgresKit/Deprecations/PostgresDataDecoder+JSONDecoder.swift, Sources/PostgresKit/PostgresDataDecoder.swift, Sources/PostgresKit/PostgresDataEncoder.swift
This adds support for using non-Foundation JSON coders when decoding and encoding JSON columns (#195).
For example, if you want to use the [pure-swift JSON coders](https://github.com/fabianfett/pure-swift-json), you can now do this during the configuration of your application:
```swift
import PureSwiftJSON
PostgresNIO._defaultJSONDecoder = PSJSONDecoder()
PostgresNIO._defaultJSONEncoder = PSJSONEncoder()
``` 
**Do note that the JSON coders used here MUST be thread safe internally.**
=> Use PostgresNIO's default JSON coders

Package.swift
PostgresKit relies on APIs introduced in PostgresNIO 1.4.0 and `Package.swift` now reflects that (#200, fixes #199).
=> Use correct minimal dependency of PostgresNIO

Sources/PostgresKit/PostgresConfiguration.swift, Tests/PostgresKitTests/Utilities.swift
Allows referencing the default PostgreSQL TCP port number (as assigned by the IANA) without hardcoding the number `5432` all over the place.
=> Add static `ianaPortNumber` property to `PostgresConfiguration`

Sources/PostgresKit/PostgresConfiguration.swift
Fixes:
```
warning: 'forClient(cipherSuites:minimumTLSVersion:maximumTLSVersion:certificateVerification:trustRoots:certificateChain:privateKey:applicationProtocols:shutdownTimeout:keyLogCallback:)' is deprecated: renamed to 'makeClientConfiguration()'
```
=> Fix `TLSConfiguration.forClient()` deprecation

Sources/PostgresKit/PostgresConnectionSource.swift
Pass the correct logger through to `PostgresConnectionSource` to bring it in line with [MySQLKit](https://github.com/vapor/mysql-kit/blob/master/Sources/MySQLKit/MySQLConnectionSource.swift#L21).
=> Fix passing the logger through on `PostgresConnectionSource`

.github/workflows/test.yml, Package.swift, Sources/PostgresKit/PostgresDialect.swift, Tests/PostgresKitTests/PostgresKitTests.swift
semver-minor because the new SQLKit version requirement is a semver-minor bump.
=> Declare UPSERT support for PostgreSQL

.github/workflows/test.yml, Tests/PostgresKitTests/Utilities.swift
Contains various fixes. Related to vapor/postgres-nio#200 and vapor/fluent-postgres-driver#186
=> Clean up CI workflow to match fluent-postgres-driver and postgres-nio

Package.swift, Sources/PostgresKit/PostgresDialect.swift, Tests/PostgresKitTests/PostgresKitTests.swift
Leverages the new dialect flags from [vapor/sql-kit#144](https://github.com/vapor/sql-kit#144) to enable full `UNION` queries according to PostgreSQL's support.
The increased SQLKit version requirement makes this a `semver-minor` change.
=> Declare supported UNION features

Package.swift
Hi folks! 
I'm not sure what this project's process for version-bumping is, but the current `vapor/postgres-nio@1.4.0` dependency can't build against the more current `swift-nio` versions because of a duplicate addition of `writeNullTerminatedString` to `ByteBuffer` by extension:
```
/path/to/.build/checkouts/postgres-nio/Sources/PostgresNIO/New/Extensions/ByteBuffer+PSQL.swift:4:19: note: found this candidate
mutating func writeNullTerminatedString(_ string: String) {
^
/path/to/.build/checkouts/swift-nio/Sources/NIOCore/ByteBuffer-aux.swift:100:26: note: found this candidate
public mutating func writeNullTerminatedString(_ string: String) -> Int { 
```
The `postgres-nio` project has since removed the duplicate method definition, so rolling forward the dependency to `1.7.2` (in this PR) …
=> Version bump postgres-nio dependency to prevent build error against swift-nio 

.github/workflows/test.yml, Package.swift, Sources/PostgresKit/PostgresConfiguration.swift, Sources/PostgresKit/PostgresConnectionSource.swift, Sources/PostgresKit/PostgresRow+SQL.swift, Tests/PostgresKitTests/Utilities.swift
- Leverage new APIs available in PostgresNIO to improve row decoding performance, making up for some speed regressions and then some, especially for queries with lots of result fields.
- Minor improvements to connection handling, also partially courtesy of improved APIs in PostgresNIO.
_Note: No new APIs, but marked semver-minor due to requiring an updated minor release of `postgres-nio`._
=> Improve row decoding performance

.github/workflows/main-codecov.yml, .github/workflows/test.yml, Package.swift
This removes support for Swift 5.2 and Swift 5.3, making Swift 5.4 the earliest supported version [as announced](https://blog.vapor.codes/posts/vapor-swift-versions-update/)
=> Drop support for Swift 5.2/5.3 + Yet another CI overhaul

Package.swift, Sources/PostgresKit/PostgresConfiguration.swift, Sources/PostgresKit/PostgresConnectionSource.swift
This change provides access to the new functionality provided in this postgres-nio PR: https://github.com/vapor/postgres-nio/pull/296. In short, apps can enable integration with Amazon RDS Proxy by setting `requireBackendKeyData` to false. See the postgres-nio PR for more details.
=> Allow `backendKeyData` to be set

Sources/PostgreSQL/Connection/PostgreSQLConnection.swift, Tests/PostgreSQLTests/ConnectionTests.swift, Tests/PostgreSQLTests/XCTestManifests.swift
ParameterStatus messages may be generated in response to a SET command or when the administrator sends the SIGHUP signals to the server. They will appear in the query response and should be ignored.
=> Ignore ParamaterStatus messages when handling response

Sources/PostgresKit/PostgresDialect.swift
Leverages the new functionality in vapor/sql-kit#154 to provide the correct syntax for both shared and exclusive locking clauses in PostgreSQL.
=> Add locking clause syntax to dialect

Package.swift, Sources/PostgresKit/PostgresConnectionSource.swift
Fix deprecation warnings from `NIOAtomic` and migrate any uses to `swift-atomics`
=> Migrate to Swift Atomics

Sources/PostgresKit/PostgresDataEncoder.swift, Tests/PostgresKitTests/PostgresKitTests.swift
This avoids unconditional `fatalError()`s firing for various legal Encodable uses.
=> Revise PostgresDataEncoder implementation to better handle various Codable conformances

Sources/PostgresKit/PostgresDataTranslation.swift, Tests/PostgresKitTests/PostgresKitTests.swift
The `PostgresData` implementation allowed this, and it's a halfway reasonable code path, so support it at the driver level.
=> Add workaround for decoding `NUMERIC` as `Double`

Sources/PostgresKit/PostgresConnectionSource.swift, Sources/PostgresKit/PostgresDatabase+SQL.swift
This is a temporary workaround while waiting for vapor/postgres-nio#360 to be finished.
=> Temporary bandaid workaround for lack of PSQLError usefulness

Package.swift, Sources/PostgresKit/PostgresDialect.swift
Implements SQLKit's new `SQLDialect.nestedSubpathExpression(in:for:)` method.
=> Add Postgres support for nested subpath (JSON) expressions

.github/workflows/projectboard.yml, .github/workflows/test.yml, Sources/PostgresKit/PostgresConnectionSource.swift, Tests/PostgresKitTests/Utilities.swift
=> Remove use of legacy codepath when establishing Postgres connections

Sources/PostgresKit/SQLPostgresConfiguration.swift, Tests/PostgresKitTests/SQLPostgresConfigurationTests.swift
For [libpq compatibility](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING), the following additional schemes are now accepted in database URLs:
- `"postgresql"`
- `"postgresql+tcp"`
- `"postgresql+uds"`
Fixes #250.
=> Enable libpq-compatible "postgresql" URL schemes

.github/workflows/test.yml, README.md, Sources/PostgresKit/Docs.docc/PostgresKit.md, Sources/PostgresKit/Docs.docc/theme-settings.json
Adds some useful documentation notes and updates CI.
(No release needed.)
=> README update

Sources/PostgresKit/PostgresDatabase+SQL.swift
We no longer need to retroactively conform `PostgresEncodingContext` to `Sendable`; we already require a version of `PostgresNIO` newer than the one that includes it natively.
This change has no functional impact and does not affect any warnings, and thus does not require a release.
=> Remove redundant Sendable conformance

Sources/PostgresKit/PostgresDialect.swift
Fluent already does this for users of FluentPostgresDriver, this just adds the same behavior to the equivalent data type at the SQLKit layer.
=> Override SQLDataType.blob to BYTEA for SQLKit users

Package.swift, Package@swift-5.9.swift, Sources/PostgresKit/PostgresConnectionSource.swift, Sources/PostgresKit/PostgresDatabase+SQL.swift
Also removes the now unneeded dependency on SwiftAtomics.
=> Update required versions of dependencies

Sources/PostgresKit/PostgresDatabase+SQL.swift
When a query is executed, the actual SQL query and its accompanying array of bound parameters (if any) are now logged as structured metadata on the logger using a generic message, rather than the query and bindings being the message. This follows the [recommended guidelines for logging in libraries](https://www.swift.org/documentation/server/guides/libraries/log-levels.html). Credit goes to @MahdiBM for the original suggestion.
Before:
```
2024-05-29T00:00:00Z debug codes.vapor.fluent : database-id=psql [PostgresKit] SELECT * FROM foo WHERE a=$1 [["bar"]]
```
After:
```
2024-05-29T00:00:00Z debug codes.vapor.fluent : database-id=psql sql=SELECT * FROM foo WHERE a=$1 binds=["bar"] [PostgresKit] Executing query
```
=> Use logging metadata when logging queries
